#ifndef _SIMPLETILE_H_
#define _SIMPLETILE_H_

#define SIMPLETILEID_NULL 0

#define SIMPLETILEID_GRASS_VARIANT_00 1
#define SIMPLETILEID_GRASS_VARIANT_01 2
#define SIMPLETILEID_GRASS_VARIANT_02 3

#define SIMPLETILEID_WATER_OCEAN_SHALLOW 100
#define SIMPLETILEID_WATER_OCEAN_MEDIUM 101
#define SIMPLETILEID_WATER_OCEAN_DEEP 102

#define SIMPLETILEID_SAND_BEACH_SIMPLE 200

typedef unsigned int SimpleTile;

#endif